### PR TITLE
Fix has_permission() return type inconsistency (Issue #67)

### LINKED ISSUE #67: Rename usage of `has_permission()` to account for a `WP_Error`
The following pages document how to use return value of the `has_permission()` method:

* https://github.com/WordPress/abilities-api/blob/v0.1.1/docs/2.getting-started.md
* https://github.com/WordPress/abilities-api/blob/v0.1.1/docs/4.using-abilities.md

This method can return a `WP_Error` or a boolean, so a check like `if ( $ability->has_permission( $input ) )` does not do what is expected. A `WP_Error` instance will evaluate to true and cause this logical check to unexpectedly pass.

The `WP_Ability::execute()` method correctly handles a `WP_Error` being returned by the permissions check.

There are a few options.

* Adjust `has_permission()` to only return a boolean, so it behaves more like a traditional capability check function such as `current_user_can()`.
  * Can be combined with retaining the existing method under a different name.
  * Can be combined with throwing an exception. Not very WordPress-y.
* Retain everything as-is but update all the developer documentation to include checks for `is_wp_error()`. I think this is risky, it's too easy for a developer to implement a simple boolean check and therefore incorrectly handle a `WP_Error`.

### PR DESCRIPTION
**Pull request by Ref34t**
## Summary
Simplifies permission checking API and updates documentation to show proper `is_wp_error()` usage patterns for preventing WP_Error truthiness issues.

## Problem Solved
The original `has_permission()` method could return either `bool` or `WP_Error`, creating a dangerous bug where WP_Error objects (which are truthy) could incorrectly pass permission checks in if statements.

## Implementation
- `check_permissions($input, $skip_validation = false)`: New recommended method with clear `bool|WP_Error` return type
- `has_permission($input)`: Deprecated wrapper for backward compatibility
- Updated documentation: Shows proper `is_wp_error()` usage patterns throughout
- Streamlined API: Uses `$skip_validation` parameter for REST API permission checks

## Testing
Existing comprehensive tests verify both methods work correctly:
- Permission validation with proper error handling
- Input validation integration with permission checks
- Backward compatibility for deprecated `has_permission()` method

Fixes #67

### CODE REVIEW

**Comment by justlevine** [comment]
(@Ref34t keep #68 in mind (and #73) before you waste too much time because of failing tests - I'll give a real review one you tag ppl, just saw the rest errors and guessing there might be an unnecessary headache you dont need to care about)

**Comment by Ref34t** [comment]
@justlevine, thanks for keeping me aware of what is happening. You can review the fix itself now

File: includes/abilities-api/class-wp-ability.php [hunk 1]
```diff
@@ -331,6 +331,21 @@ public function has_permission( $input = null ) {
...
+	 * Checks whether the ability has the necessary permissions.
+	 * If the permission callback is not set, the default behavior is to allow access
+	 * when the input provided passes validation.
+	 *
+	 * @since N.E.X.T
+	 *
+	 * @param mixed $input Optional. The input data for permission checking. Default `null`.
+	 * @return bool Whether the ability has the necessary permission.
+	 */
+	public function has_permission( $input = null ): bool {
```
Comment (justlevine) [inline includes/abilities-api/class-wp-ability.php]: Since the other method is public, having _another_ public method that's sole goal is coercing things to a boolean seems superfluous, and unnecessary tech-debt for an initial WP6.9 release. 

Resurfaced this back on the issue at https://github.com/WordPress/abilities-api/issues/67#issuecomment-3289608930

File: includes/abilities-api/class-wp-ability.php [hunk 2]
```diff
@@ -395,7 +410,7 @@ protected function validate_output( $output ) {
 	 * @return mixed|\WP_Error The result of the ability execution, or WP_Error on failure.
 	 */
 	public function execute( $input = null ) {
-		$has_permissions = $this->has_permission( $input );
+		$has_permissions = $this->get_permission_status( $input );
```
Comment (justlevine) [inline includes/abilities-api/class-wp-ability.php]: Case in point to https://github.com/WordPress/abilities-api/pull/76#discussion_r2347378304 - we're only using this internally while our only use of `::has_permission()` is in a REST API endpoint (which long term [should probably be an ability anyway](https://github.com/WordPress/abilities-api/issues/75)

File: includes/abilities-api/class-wp-ability.php [hunk 3]
```diff
@@ -305,16 +305,16 @@ protected function validate_input( $input = null ) {
...
 	 *
-	 * @since 0.1.0
+	 * @since N.E.X.T
 	 *
 	 * @param mixed $input Optional. The input data for permission checking. Default `null`.
-	 * @return bool|\WP_Error Whether the ability has the necessary permission.
+	 * @return bool|\WP_Error Whether the ability has the necessary permission, or WP_Error with details.
 	 */
-	public function has_permission( $input = null ) {
+	public function get_permission_status( $input = null ) {
```
Comment (justlevine) [inline includes/abilities-api/class-wp-ability.php]: Permission "status" isn't a concept that currently exists in the WordPress core codebase, so I would avoid creating it. Some alternatives:

- `::check_permissions()` - completely unused, but it:
   - follows good semantic naming for an action
	 - `::check_*` is _mostly_ used to return `{some_type}|\WP_Error`, but there are some instances where its `: void` or `: bool`
	 - Specifically, `::check_{someitem}_permissions()` is common on REST and returns `bool`.
- `::permissions_check()`,  `::get_permissions_check()` or the more verbose `::get_ability_permissions_check()`
   - Mirrors what's used by `WP_Rest_Controller` - because it has multiple perms of checks in a class (CRUD) and `WP_oEmbed_Controller::get_proxy_item_permissions_check()` assumedly because it's a rest endpoint even though it doesn't inherit the class.
   - `::permissions_check()` is used in several `WP_Rest_Controller` children instead of `get_*()` , and this is the one I recommend here. (There are a couple uses of `::do_permissions_check()` but afaik they're all only `protected` and leaked in on much larger PRs where the specific rest endpoint wasnt necessarily code reviewed in detail since there wasn't an expectation of it being extended).
   
**PS: note the use of permission*s* (plural). I couldn't find anywhere in core that uses the singular `permission` in a method name.

**Review by justlevine — COMMENTED** [review]
Aside from [whether or not](https://github.com/WordPress/abilities-api/issues/67#issuecomment-3289608930) we need _both_ a public checker function and a (also public) wrapper whose sole purpose is to coerce it to a `bool`, I think we need a better name for the function itself.

image

File: includes/abilities-api/class-wp-ability.php (hunk 2 above)
Comment (justlevine) [reply includes/abilities-api/class-wp-ability.php]: >  while our only use of ::has_permission() is in a REST API endpoint

Follow up: 👆(and not #73) is the reason why the tests are failing. `WP_REST_Abilities_Run_Controller::run_ability_permissions_check()` explicitly only checks against `false` and specifically allows the WP_Error through so invalid method errors are only shown to a user with the correct permissions when the callback is actually run:

https://github.com/ref34t/abilities-api/blob/8fcfcac9136dee73abb798bbaded0a21c17b5cd8/includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php#L93-L111

@Ref34t In the context of _this_ PR, change `::run_ability_permissions_check()` to `if ( false === $ability->get_permission_status()` (or whatever it's renamed to).

---
More broadly, I'm like 95% sure this leaked in from the A8C prior art and should be **removed and punted to MCP Adapter**, as "Resource" and "Tool" are not concepts of the Abilities API and don't belong in core. @emdashcodes / @gziolo please confirm, but either way it can be handled as part of #75.

**Comment by Ref34t** [comment]
@justlevine Thanks for the feedback! Based on your comments and WP Core research, I’ve updated the PR to:
	•	Rename has_permission() → check_permissions() to avoid the misleading has_* boolean expectation.
	•	Standardize return types to true | false | WP_Error, matching Core patterns (like permissions_check()) and preventing WP_Error from being treated as true.
	•	Update execute() to always enforce permissions safely, centralizing logic and ensuring abilities can’t be bypassed.
	•	Align with Core standards while keeping developer usage simple and predictable.

These changes address #67, improve security, and follow Core conventions for REST and capability checks.

**Comment by gziolo** [comment]
You are exploring more advanced refactorings rather than a simple documentation update to account for possible incorrect usage. I left some other ideas to consider in https://github.com/WordPress/abilities-api/issues/67#issuecomment-3290617975 and https://github.com/WordPress/abilities-api/issues/67#issuecomment-3291135690.

File: includes/abilities-api/class-wp-ability.php [hunk 4]
```diff
@@ -305,19 +306,22 @@ protected function validate_input( $input = null ) {
...
 	 * @param mixed $input Optional. The input data for permission checking. Default `null`.
-	 * @return bool|\WP_Error Whether the ability has the necessary permission.
+	 * @param bool  $skip_validation Optional. Whether to skip input validation. Default `false`.
+	 * @return bool|\WP_Error Whether the ability has the necessary permission, or WP_Error with details.
 	 */
-	public function has_permission( $input = null ) {
-		$is_valid = $this->validate_input( $input );
-		if ( is_wp_error( $is_valid ) ) {
-			return $is_valid;
+	public function check_permissions( $input = null, $skip_validation = false ) {
```
Comment (gziolo) [inline includes/abilities-api/class-wp-ability.php]: Could you elaborate on the reasoning for this change? It doesn't look related to the issue reported.

> Streamlined API: Uses $skip_validation parameter for REST API permission checks

This comment seems related, but it doesn't explain why to sacrifice the simplicity of the method to simplify implementation for a specific usage in the REST controller.

File: includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php
Comment (justlevine) [inline includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php:1]: Only reviewing this on my phone, but want to make sure we're limiting the refactoring in this PR to specifically address in #67. We can do other stuff in other PRs that isn't blocking v0.2.0.

Will pull for a real review hopefully this evening.

**Review by gziolo — CHANGES_REQUESTED** [review]
I wanted to echo the feedback shared by @justlevine in https://github.com/WordPress/abilities-api/pull/76#discussion_r2355503610. Can we limit this PR to renaming `has_permission()` to `check_permission()` with the included deprecation logic and documentation changes?

That part is ready to go.

File: includes/abilities-api/class-wp-ability.php (hunk 2 above)
Comment (gziolo) [reply includes/abilities-api/class-wp-ability.php]: > More broadly, I'm like 95% sure this leaked in from the A8C prior art and should be removed and punted to MCP Adapter, as "Resource" and "Tool" are not concepts of the Abilities API and don't belong in core. @emdashcodes / @gziolo please confirm, but either way it can be handled as part of https://github.com/WordPress/abilities-api/issues/75.

I noticed this when reviewing the PR, and I found it useful. I’m not 100% sure we should use this specific set of criteria to distinguish between GET and POST, but I didn’t have the bandwidth to start a larger conversation about the optimal approach as this seems more like an implementation detail. I think we could tap into [Add property for marking Ability hints like destructive, read-only, idempotent](https://github.com/WordPress/abilities-api/issues/62) to iron out the detection mechanism.

Overall, I’m tempted to borrow some of the solutions from MCP without using nomenclature and structure too tied this particular protocol.

File: includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php
Comment (Ref34t) [reply includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php:1]: resolved

**Comment by gziolo** [comment]
@Ref34t, I see you are actively working on addressing feedback. I triggered review from GitHub Copilot to see if it catches anything. I'm still not sure whether `check_permission` or `check_permissions` would be a better choice. The part that triggered my thinking was documentation which uses plural everywhere.

File: includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php
Comment (gziolo) [reply includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php:1]: nice!

**Comment by Ref34t** [comment]
@gziolo I had it before plural and now due to your last feedback I changed it again 😔 what do you think the final call here? 🤔

**Comment by gziolo** [comment]
The REST API uses `permission_callback`, so let's stick with the singular form, as it is also used for the ability. It looks like no further changes are necessary because in the docs I see the plural form when explaining the concept for REST API:

https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/#permissions-callback

File: tests/unit/abilities-api/wpRegisterAbility.php [hunk 5]
```diff
@@ -308,6 +308,32 @@ public function test_permission_callback_no_input_schema_match(): void {
...
 
+	/**
+	 * Tests that deprecated has_permission() method still works
+	 */
+	public function test_has_permission_deprecated_coverage(): void {
+		do_action( 'abilities_api_init' );
+
+		$result = wp_register_ability( self::$test_ability_name, self::$test_ability_args );
+
+		// Suppress deprecation notice for coverage testing
```
Comment (gziolo) [inline tests/unit/abilities-api/wpRegisterAbility.php]: I'm curious whether the standard WP test helper is avialable here. Something like that would work in core:
```php
$this->expectedDeprecated( 'WP_Ability::has_permission' );
```

Comment (gziolo) [reply tests/unit/abilities-api/wpRegisterAbility.php]: Maybe it's done with `@expectedDeprecated` and PHPDoc. It might be fine as is given the limited testing context.

Comment (Ref34t) [reply tests/unit/abilities-api/wpRegisterAbility.php]: yes, after checking that's right. Resolved here https://github.com/WordPress/abilities-api/pull/76/commits/d55a0bb4d2cde3fc3e965193472ae0843a015c07

**Review by gziolo — APPROVED** [review]
All feedback addressed. It looks good to go from my angle. @justlevine how about you?

@jonathanbossenger, could you perform a quick sanity check on the docs changes?

**Comment by justlevine** [comment]
> The REST API uses permission_callback, so let's stick with the singular form, as it is also used for the ability.

I'm sorry to be pedantic, but as [I previously noted](https://github.com/WordPress/abilities-api/pull/76#discussion_r2347392156) the REST API uses `check_{*_}_permissions()` _plural_, even though the registry arg is `permission_callback`. It's also more grammatically accurate when paired with the verb `check_*`.

I'm happy to do this myself in a follow-up PR if we feel bad about making @Ref34t keep swapping back-and-forth, but I do feel strongly about uniformity with core APIs.

File: includes/abilities-api/class-wp-ability.php (hunk 2 above)
Comment (justlevine) [reply includes/abilities-api/class-wp-ability.php]: > Overall, I’m tempted to borrow some of the solutions from MCP without using nomenclature and structure too tied this particular protocol.

Yeah it's that latter part that's critical, and considering that [MCP's value as a whole is doubtful](https://wordpress.slack.com/archives/C08TJ8BPULS/p1758990133058409), I would want a discussion of what a "resource" or "tool" is meant to be in our context, and whether it is inherently useful - if/when this gets revisited.

Either way, no longer part of this PR, so can be resolved.

File: docs/2.getting-started.md [hunk 6]
```diff
@@ -133,10 +133,27 @@ add_action( 'admin_init', 'my_plugin_use_ability' );
 function my_plugin_use_ability() {
     $ability = wp_get_ability( 'my-plugin/get-site-title' );
 
-    if ( $ability && $ability->has_permission() ) {
-        $site_title = $ability->execute();
-        // $site_title now holds the result of get_bloginfo('name')
-        // error_log( 'Site Title: ' . $site_title );
+    if ( $ability ) {
+        // Check permissions first - always use is_wp_error() to handle errors properly
+        $permission = $ability->check_permission();
```
Comment (justlevine) [inline docs/2.getting-started.md:138]: I think this (and the previous example) is incorrect. By calling `$ability->execute()`, `$ability->get_permission()` gets called, there's rarely a reason to explicitly check permissions as a separate step.

```php
if ( $ability  ) {
        $site_title = $ability->execute();
        // $site_title now holds the result of get_bloginfo('name')
        // error_log( 'Site Title: ' . $site_title );
    }
}

File: docs/4.using-abilities.md [hunk 7]
```diff
@@ -124,9 +124,14 @@ if ( $ability ) {
...
-**Checking Permissions (`$ability->has_permission()`)**
+**Checking Permissions (`$ability->check_permission()`)**
 
-Before executing an ability, you can check if the current user has permission:
+Before executing an ability, you can check if the current user has permission. The `check_permission()` method returns either `true`, `false`, or a `WP_Error` object, so you must use `is_wp_error()` to handle errors properly:
+
+```php
+// Method signature:
+// check_permission( $input = null )
+```
```
Comment (justlevine) [inline docs/4.using-abilities.md:134]: Is this intentional or did it leak?

File: docs/4.using-abilities.md [hunk 8]
```diff
@@ -136,12 +141,17 @@ if ( $ability ) {
         'option_value' => 'New Site Name',
     );
 
-    // Check permission before execution
-    if ( $ability->has_permission( $input ) ) {
+    // Check permission before execution - always use is_wp_error() first
```
Comment (justlevine) [inline docs/4.using-abilities.md:144]: I know the doc in general uses a lot of unnecessary nesting, but I think this also make's it clearer than sandwiching the happy-path between two error states.

```php
    // Use a strict check to catch both false and WP_Error
    $permission = $ability->check_permission( $input );
    if ( true === $permission ) {
        // Permission granted - safe to execute.
        $result = $ability->execute( $input );
        if ( is_wp_error( $result ) ) {
            // Handle execution error
            echo 'Execution error: ' . $result->get_error_message();
        } else {
            // Use $result
            if ( $result['success'] ) {
                echo 'Option updated successfully!';
                echo 'Previous value: ' . $result['previous_value'];
            }
        }
    } else {
        // Don't leak permission errors to unauthenticated users.
        if ( is_wp_error( $permission ) ) {
            error_log( 'Permission check failed: ' . $permission->get_error_message() );
        }

        echo 'You do not have permission to execute this ability.';
    }
}
```

Though imo we shouldn't be actively promoting `check_permission()` and instead have users fully handle `execute()`

```php
$ability = wp_get_ability( 'my/ability' );

$result = $ability->execute( $input ) ;
// If we want to only handle perm errors and not also invalid inputs etc.
if ( is_wp_error() && 'ability_invalid_permissions' === $result->get_error_code() ) {
 // handle the error
}

File: includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php [hunk 9]
```diff
@@ -163,7 +163,7 @@ public function run_ability_permissions_check( $request ) {
 		}
 
 		$input = $this->get_input_from_request( $request );
-		if ( ! $ability->has_permission( $input ) ) {
+		if ( ! $ability->check_permission( $input ) ) {
```
Comment (justlevine) [inline includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php:166]: Are we intentionally only handling false and saving the WP_Errors for `->execute()`? cc @emdashcodes 

```suggestion
		if ( true !== $ability->check_permission( $input ) ) {
```

**Review by justlevine — COMMENTED** [review]
Looks good! Left some comments that have nothing to do with [naming things](https://github.com/WordPress/abilities-api/pull/76#issuecomment-3342052640).

**Comment by gziolo** [comment]
> I'm sorry to be pedantic, but as https://github.com/WordPress/abilities-api/pull/76#discussion_r2347392156 the REST API uses check_{*_}_permissions() plural, even though the registry arg is permission_callback. It's also more grammatically accurate when paired with the verb check_*.

I'm not a native speaker, so I'm happy to follow your guidance here. I will land this PR and try address all the feedback for docs in another PR.

File: includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php (hunk 9 above)
Comment (gziolo) [reply includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php:166]: Let's fix it. I don't think it was intentional.

Comment (gziolo) [reply includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php:166]: In my testing, the proposed code changes fail the result of 4 tests in the run controller. We would have to better handle the reason the request errored so it doesn't default to 403. It probably means, we would have to move some logic to `run_ability_permissions_check`.

**Comment by gziolo** [comment]
A follow-up https://github.com/WordPress/abilities-api/pull/94 is ready for review. It addresses all feedback from @justlevine, but https://github.com/WordPress/abilities-api/pull/76#discussion_r2384361124, which I think needs more thought.

File: includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php (hunk 9 above)
Comment (gziolo) [reply includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php:166]: An alternative would be to remove `run_ability_permissions_check()` (skip `permission_callback`) in the run controller, taking into account that `run_ability` (part of the `callback`) validates permissions anyway. It still would have to handle 403 when `check_permissions()` from the ability returns `false`.

Technically speaking, we are good. However, we can improve the implementation/documentation to avoid future misunderstandings.
