### PR TITLE
Fix `$input` type hint in `WP_Ability`

### LINKED ISSUE #58: Fix `$input` type hint in `WP_Ability`
The `WP_Ability` class uses `array $input` in several places.

While this is likely working for 90% of use-cases, the shape of the input depends on the input schema that is used. That input schema can signify any type that can be expressed in JSON schema - but the PHP `array` type hint only works for the JSON schema types `object` and `array`.

While based on my experience using a parameter scheme of `object` is extremely common, any other types are possible and supported by function calling capabilities of most popular LLMs.

As such, I think the `array` type hint on `$input` is a bug and should be fixed. It needs to be without a type hint, as it can be `mixed`.

### PR DESCRIPTION
**Pull request by gziolo**
Closes https://github.com/WordPress/abilities-api/issues/58.

> The `WP_Ability` class uses `array $input` in several places.
>
> While this is likely working for 90% of use-cases, the shape of the input depends on the input schema that is used. That input schema can signify any type that can be expressed in JSON schema - but the PHP `array` type hint only works for the JSON schema types `object` and `array`.

Given that `$input` is used with two public methods `execute`, `has_permission`, and other methods internally, the code in `WP_Ability` class was adjusted accordingly to use a unified approach. This changes the type hint from array to mixed to support all JSON schema types, including `null`, `boolean`, `number`, `integer`, `string`, `array`, and `object`.

- Updated all method signatures and documentation to use mixed instead of array for input parameters.
- Made the `$input` argument optional in `execute_callback` and `permission_callback` when the `input_schema` is not defined and the value is `null`.
- Updated REST API controller to properly handle mixed input types without assuming array format.
- Add new tests covering all possible input types.
- Modified test callbacks to match the new signatures where appropriate.

## Testing

All unit tests should pass:

```bash
npm run test:php
```

### CODE REVIEW

**Comment by gziolo** [comment]
This still needs some additional test coverage to account for the different scenarios for input values passed to `execute`. It uses internally `has_permission`, so the only case to ensure it's covered would be when the input is not set at all, and the new default `null` is automatically set.

**Comment by gziolo** [comment]
@galatanovidiu, I would appreciate a sanity check in relation to the MCP Adapter. Would the changes proposed introduce the need for some additional handling there, as the input type might become a simple type now? The same question applies to the input schema, but that part I'm less afraid of, unless the input in MCP has some specific requirements.

File: includes/abilities-api/class-wp-ability.php [hunk 1]
```diff
@@ -321,10 +321,10 @@ public function has_permission( array $input = array() ) {
 	 *
 	 * @since 0.1.0
 	 *
-	 * @param array<string,mixed> $input The input data for the ability.
+	 * @param mixed $input The input data for the ability.
 	 * @return mixed|\WP_Error The result of the ability execution, or WP_Error on failure.
 	 */
-	protected function do_execute( array $input ) {
+	protected function do_execute( $input ) {
```
Comment (galatanovidiu) [inline includes/abilities-api/class-wp-ability.php]: **Ambiguous handling of `null` input in ability execution:**

Currently, when `$input` is `null` in the `do_execute()` method, it gets passed to the callback as `call_user_func($callback, null)`, meaning the callback receives null as its first argument.
This creates an ambiguity:

Case 1: Developer wants to call a callback with no arguments (e.g., `wp_get_current_user()`)
Case 2: Developer wants to pass `null` as a meaningful argument to the callback explicitly

**Problem scenarios:**

Callbacks that expect no parameters (like `wp_get_current_user()`) will receive an unexpected null parameter
No way to distinguish between **"no arguments"** vs **"null argument"**

**Proposed solutions:**

Use Reflection API to inspect the callback's parameter signature and make intelligent decisions:

If callback expects 0 parameters and input is null: call without arguments: call_user_func($callback)
Otherwise pass input as argument: call_user_func($callback, $input)

Comment (gziolo) [reply includes/abilities-api/class-wp-ability.php]: The same problem existed before when this was an array and the default value was `[]`. I agree it would be nice to remove the ambiguity of the `null` value by not using it as the default value.

It would be a nice enhancement to support some built-in functions, as a possible target for `execute_callback`. However, it's a more nuanced topic, because `do_execute` would have to follow the same type `mixed ...$args` like `call_user_func` does, while it's currently a single param. It would be convenient for PHP implementers, but this becomes harder to describe with JSON schema and handle through the REST API. What is the approach you had in mind here?

**Comment by gziolo** [comment]
In [e117cac](https://github.com/WordPress/abilities-api/pull/61/commits/e117cac36c6a2e7a20bca713812c2ed35e14f573) added tests that cover several types of input:
- boolean
- string
- number
- array

Still to cover:
- null
- object
- integer (the current test for number should probably use integer)

**Comment by gziolo** [comment]
@felixarntz, this is in a shape where it could use some feedback, so we can align if this is going in the right direction.

File: includes/abilities-api/class-wp-ability.php (hunk 1 above)
Comment (felixarntz) [reply includes/abilities-api/class-wp-ability.php]: Why not make the decision for whether to pass `$input` based on the schema? I think using reflection for this is unnecessary and less efficient.

Case in point: `validate_input()` already returns `true` without checking anything if the input schema is empty.

Similarly, we could implement this as follows: If the input schema is empty, we don't pass `$input` to any callbacks (`execute_callback`, `permission_callback`).

* Makes sense because if there's no input schema, you don't expect any input.
* If you at the same time pass a callback that expects an input, you're doing it wrong.

File: includes/abilities-api.php [hunk 2]
```diff
@@ -35,8 +35,8 @@
  *   description?: string,
  *   input_schema?: array<string,mixed>,
  *   output_schema?: array<string,mixed>,
- *   execute_callback?: callable( array<string,mixed> $input): (mixed|\WP_Error),
- *   permission_callback?: callable( array<string,mixed> $input ): (bool|\WP_Error),
+ *   execute_callback?: callable( mixed $input ): (mixed|\WP_Error),
+ *   permission_callback?: callable( mixed $input ): (bool|\WP_Error),
```
Comment (felixarntz) [inline includes/abilities-api.php]: We need to change these to allow the callbacks to not expect any `$input` (relevant when `input_schema` is empty).

**Review by felixarntz — COMMENTED** [review]
This looks good regarding getting rid of the array requirement. I left some thoughts regarding the handling of expecting no input / no parameters.

File: tests/unit/rest-api/wpRestAbilitiesRunController.php [hunk 3]
```diff
@@ -608,7 +608,7 @@ public function test_output_validation_failure_returns_error(): void {
 					),
 					'required'   => array( 'status' ),
 				),
-				'execute_callback'    => static function ( $input ) {
+				'execute_callback'    => static function () {
```
[the remark this answers is not in the document]
Comment (gziolo) [reply tests/unit/rest-api/wpRestAbilitiesRunController.php:607]: Good catch. At the same time, the plan is to make that optional as proposed in https://github.com/WordPress/abilities-api/pull/61#discussion_r2330648111.

File: includes/abilities-api.php (hunk 2 above)
Comment (gziolo) [reply includes/abilities-api.php]: Good point. It should be optional to define the `$input` based on the conversations. I'll update these type hints accordingly 👍🏻

Comment (gziolo) [reply includes/abilities-api.php]: Addressed in https://github.com/WordPress/abilities-api/pull/61/commits/75d89cfb985d4908f5a36665c1d234bd30f886c3.

File: includes/abilities-api/class-wp-ability.php (hunk 1 above)
Comment (gziolo) [reply includes/abilities-api/class-wp-ability.php]: The idea shared by @felixarntz that addresses the concerns should be fully implemented in https://github.com/WordPress/abilities-api/pull/61/commits/19357994511dc341786e27d0f746d903ca81c138. I still need to increase test coverage.

**Comment by gziolo** [comment]
It's ready for the final review. I addressed the feedback, increased test coverage, and updated existing documentation.

File: includes/abilities-api/class-wp-ability.php [hunk 4]
```diff
@@ -269,10 +269,10 @@ public function get_meta(): array {
 	 *
 	 * @since 0.1.0
 	 *
-	 * @param array<string,mixed> $input Optional. The input data to validate.
+	 * @param mixed $input The input data to validate.
 	 * @return true|\WP_Error Returns true if valid or the WP_Error object if validation fails.
 	 */
-	protected function validate_input( array $input = array() ) {
+	protected function validate_input( $input ) {
```
Comment (felixarntz) [inline includes/abilities-api/class-wp-ability.php]: Nit-pick: Not strictly necessary, but for clarity I think we should make `$input` optional even on the internal methods.
```suggestion
	protected function validate_input( $input = null ) {
```

File: includes/abilities-api/class-wp-ability.php [hunk 5]
```diff
@@ -322,10 +326,10 @@ public function has_permission( array $input = array() ) {
 	 *
 	 * @since 0.1.0
 	 *
-	 * @param array<string,mixed> $input The input data for the ability.
+	 * @param mixed $input The input data for the ability.
 	 * @return mixed|\WP_Error The result of the ability execution, or WP_Error on failure.
 	 */
-	protected function do_execute( array $input ) {
+	protected function do_execute( $input ) {
```
Comment (felixarntz) [inline includes/abilities-api/class-wp-ability.php]: See above:
```suggestion
	protected function do_execute( $input = null ) {
```

File: includes/abilities-api/class-wp-ability.php [hunk 6]
```diff
@@ -269,10 +269,10 @@ public function get_meta(): array {
...
 	 *
-	 * @param array<string,mixed> $input Optional. The input data to validate.
+	 * @param mixed $input The input data to validate.
 	 * @return true|\WP_Error Returns true if valid or the WP_Error object if validation fails.
 	 */
-	protected function validate_input( array $input = array() ) {
+	protected function validate_input( $input ) {
 		$input_schema = $this->get_input_schema();
 		if ( empty( $input_schema ) ) {
 			return true;
```
Comment (felixarntz) [inline includes/abilities-api/class-wp-ability.php]: Giving this another thought, should we really do it like that? I think it's problematic from a security standpoint:
* The `input_schema` is critical in validating that the input is expected, including from a security perspective.
* It is already required, which makes sense.
* The only reasonable explanation for providing an empty `$input_schema` is that the ability does not expect any input. (It makes sense that it's required regardless, to make that "opt out" explicit.) But technically, it's still possible to pass `$input` to the ability.
* **Problem:** This code interprets the lack of `$input_schema` as "let's not validate" - I think this is a security concern. Instead, it should interpret the lack of `$input_schema` as: If there is any input (i.e. `$input !== null`), this is invalid and it should return a `WP_Error`.

File: includes/abilities-api/class-wp-ability.php [hunk 7]
```diff
@@ -314,6 +314,10 @@ public function has_permission( array $input = array() ) {
...
 		}
 
+		if ( empty( $this->get_input_schema() ) && null === $input ) {
+			return call_user_func( $this->permission_callback );
+		}
```
Comment (felixarntz) [inline includes/abilities-api/class-wp-ability.php]: Related to my previous comment, we should not allow any unvalidated input to be sent through. In other words, this clause should only be dependent on whether there's an input schema.
```suggestion
		if ( empty( $this->get_input_schema() ) ) {
			return call_user_func( $this->permission_callback );
		}
```

**Review by felixarntz — CHANGES_REQUESTED** [review]
@gziolo The type hint fix here LGTM, but I am realizing that there's IMO a security flaw in how the validation of the input is handled. It's not introduced by this PR, but it would be critical to fix, unless I'm missing something.

cc @justlevine

File: includes/abilities-api/class-wp-ability.php (hunk 4 above)
Comment (gziolo) [reply includes/abilities-api/class-wp-ability.php]: I wasn't sure about that, but I'm happy to propagate the default as `null` in all necessary places 👍🏻

File: includes/abilities-api/class-wp-ability.php (hunk 6 above)
Comment (gziolo) [reply includes/abilities-api/class-wp-ability.php]: I'm open to hardening this one. I wasn't sure what's the best way to go about it, so all it worth taking into consideration. It means it will become very strict in the sense that the only case when we allow not passing the input schema is when there is no input at all. Otherwise, even when passing `null` as value, we would have to validatr with input schema provided.

Comment (felixarntz) [reply includes/abilities-api/class-wp-ability.php]: To me passing `null` as `$input` is the same as not passing any `$input` at all. If the developer provided an input schema that was only allowing `null`, it would be pointless to do so anyway because it doesn't have any meaning. And if the value `null` is being passed in a situation where passing another value is possible, that would only work in combination with providing a (oneOf) schema anyway.

So to clarify what I meant: If there's no input schema, it's fine as long as `$input === null`. Whether it was passed as `null` or whether it's just the `null` default shouldn't matter.

Comment (gziolo) [reply includes/abilities-api/class-wp-ability.php]: > So to clarify what I meant: If there's no input schema, it's fine as long as `$input === null`. Whether it was passed as `null` or whether it's just the `null` default shouldn't matter.

I agree with the rationale. I committed your proposed changes, and I will update the rest of the codebase accordingly to make it work this way.

File: includes/abilities-api/class-wp-abilities-registry.php [hunk 8]
```diff
@@ -56,8 +56,8 @@ final class WP_Abilities_Registry {
 	 *   description?: string,
 	 *   input_schema?: array<string,mixed>,
 	 *   output_schema?: array<string,mixed>,
-	 *   execute_callback?: callable( array<string,mixed> $input): (mixed|\WP_Error),
-	 *   permission_callback?: ?callable( array<string,mixed> $input ): (bool|\WP_Error),
+	 *   execute_callback?: callable( mixed $input= ): (mixed|\WP_Error),
+	 *   permission_callback?: ?callable( mixed $input= ): (bool|\WP_Error),
```
Comment (justlevine) [inline includes/abilities-api/class-wp-abilities-registry.php:60]: And elsewhere I think

```suggestion
	 *   execute_callback?: callable( mixed $input ): (mixed|\WP_Error),
	 *   permission_callback?: ?callable( mixed $input ): (bool|\WP_Error),
```

**Review by justlevine — COMMENTED** [review]
> This changes the type hint from array to mixed to support all JSON schema types, including null, boolean, number, integer, string, array, and object.

Seeing the diff reinforces my concern about how PHP's `mixed` is broader than "all JSON schema types". 

( I'm not sure why we want to allow for non-named arguments here, and still think that we should use `WP_REST_Controller` as the prior art here where only _named_ inputs (`'args': array<string,mixed>|null` ) are supported. I cannot think of a justifiable DX we're we (humans, tools, agents, implementations) would prefer to be fully-dependent on also having the `WP_Ability::$input_schema` to understand the shape, instead of inferring/juggling an array key. ( e.g. get_post( $input ) is always going to less semantic than get_post( $input['user_id'] )` )

If we are going to allow more than named argments , then we can at least be accurate about the PHP type, and use `null|bool|int|float|string|mixed[]|object`, instead of littering the codebase with an avoidable mixed.

Last time I bring all that up I promise 🤐)

---

Regarding the input schema validation, agree that semantically it should be `if ( null === $input_schema ) { return true; }` while `if ( empty( $input_schema ) ) { return new \WP_Error()` 

~A few search-replaces ( `$input= ` => `$input` ) and~ ([nevermind](https://github.com/WordPress/abilities-api/pull/61#discussion_r2334684345) ) LGTM

File: includes/abilities-api/class-wp-abilities-registry.php (hunk 8 above)
Comment (gziolo) [reply includes/abilities-api/class-wp-abilities-registry.php:60]: It's intentional to account for the case where we don't pass the first argument if there is no input schema and the value is `null`.

File: includes/abilities-api/class-wp-ability.php (hunk 6 above)
Comment (gziolo) [reply includes/abilities-api/class-wp-ability.php]: [c377af9](https://github.com/WordPress/abilities-api/pull/61/commits/c377af9dd8d0ad62f0ba302854cc465cf500dff5) should do the trick.

I will look into failing unit tests tomorrow as REST API controllers somehow depend on the old behavior.

File: includes/abilities-api/class-wp-abilities-registry.php (hunk 8 above)
Comment (gziolo) [reply includes/abilities-api/class-wp-abilities-registry.php:60]: It may not be what I wanted to express. The idea is that folks can define the callback without any params, and linters would be happy. It isn't the case when there is `mixed $input`.

Comment (justlevine) [reply includes/abilities-api/class-wp-abilities-registry.php:60]: Never seen that syntax before. Neat!

Comment (justlevine) [reply includes/abilities-api/class-wp-abilities-registry.php:60]: image

Comment (gziolo) [reply includes/abilities-api/class-wp-abilities-registry.php:60]: I found an example confirming it's a thing [here](https://phpstan.org/writing-php-code/phpdoc-types#callables), in particular this:

> `callable(int, int=): string` (second parameter is optional)

I guess `?` is reserved for optional keys on arrays and properties on objects.

**Comment by gziolo** [comment]
@justlevine, so you suggest we replace `mixed` with the explicit list of the allowed types that the REST API can handle? The list of primitive types is [here](https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/#primitive-types), which should align with the unit tests I added. The type would be defined on the REST API schema as:

`(integer|number|boolean|string|array|object|null)` 

or more precisely

`'type' => [ 'integer', 'number', 'boolean', 'string', 'array', 'object', 'null' ]`

The order might be wrong as it matters here because of [Type Juggling](https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/#type-juggling). Based on your feedback, we would also need to make the object type more structured. Although I see that it needs to implement `JsonSerializable`, this implies that it must contain keys that are strings.

**Comment by gziolo** [comment]
I added specific types in the REST API schema in [a21105f](https://github.com/WordPress/abilities-api/pull/61/commits/a21105f8e43e6e3bf82c7e9c220d54b73e222c6a). @justlevine, what else would you like to have included? I may not fully understand your expectations. This looks good enough for me at this point.

File: includes/abilities-api/class-wp-ability.php [hunk 9]
```diff
@@ -334,6 +348,10 @@ protected function do_execute( array $input ) {
 			);
 		}
 
+		if ( empty( $this->get_input_schema() ) && null === $input ) {
```
Comment (felixarntz) [inline includes/abilities-api/class-wp-ability.php]: From a defensive coding perspective, we should not let any input go through that hasn't been validated. If there's no input schema, that's always the case.

```suggestion
		if ( empty( $this->get_input_schema() ) ) {
```

In practice, this change does not make any difference today. But it helps prevent accidental problems down the line, e.g. if someone later changes `validate_input()` to behave differently.

**Review by felixarntz — APPROVED** [review]
@gziolo This looks great to me, thank you for the updates!

Just one minor note that I think would be worth updating before merge.

File: includes/abilities-api/class-wp-ability.php (hunk 9 above)
Comment (gziolo) [reply includes/abilities-api/class-wp-ability.php]: Good catch. It’s an artifact from my initial implementation.

**Comment by gziolo** [comment]
> what else would you like to have included? I may not fully understand your expectations. This looks good enough for me at this point.

@justlevine, I'm still happy to discuss and iterate when you have a chance to respond. Now, I will land this PR as it addresses a larger issue.
